pushing a mess. out of time!

diff --git a/core/service-conf b/core/service-conf
--- a/core/service-conf
+++ b/core/service-conf
@@ -1,34 +1,53 @@
 #!/bin/sh
 set -e
 # set -x
-# Usage: $1 is the main settings. $2 is the service settings.
-# example usage is:
-# service-conf /package/airstack/core/config.json /package/airstack/dropbear/config.json
-# TODO: if the json has any missing options, it will assume defaults.
+# Usage: pass in a list of services to configure
+# Example: service-conf serf haproxy
+
+# add airstack helpers if they exist:
+ERROR_MESSAGE_DEFAULT="[ERROR] service-conf -"
+[ -f "/package/airstack/core/airstack-helpers" ] && { . /package/airstack/core/airstack-helpers ;} || { printf "missing airstack-helpers. exiting.\n" && exit 113 ;}
+
+ln /service /service
+error_check "testing error"
 
 # TODO: use the "state" key in config.json
 init() {
-  BASEDIR="/etc/sv"
-  # BASEDIR="/tmp"
-  MAIN_SETTINGS=$1
-  SERVICE_SETTINGS=$2
-  ( [ -z "$MAIN_SETTINGS" ] || [ -z "$SERVICE_SETTINGS" ] ) && (echo 'all params not set.' && exit 1)
-  return 0
+  echo "hi"
 }
 
+###
+# Set up necessary service configs after running the enable var contents.
+# Usage: pass in the service name in all lowercase.
+###
+# run the enable command for a service.
 service_enable_pre() {
   set +e
-  # eval the enable command
-  eval "$SERVICE_ENABLE"
+  # don't do anything if blank
+  [ -z "$1" ] && return 1
+
+  local service_name; service_name="$1"
+  local service_name_upcase; service_name_upcase=$( echo "$1" | tr "[:lower:]" "[:upper:]" )
+  local enable_name; enable_name=$(find /service/$service_name/env/* -name '*_ENABLE' | head -n1)
+  # local enable_name; enable_name=$(find /service/$service_name/env/* -name '*_ENABLE' | head -n1)
+
+  # TODO: jq deep merge-ish. example of somethin...
+  # cat /etc/airstack/runtime.json | jq --argfile socklog_unix /package/airstack/socklog-unix/config.json ' .services + $socklog_unix[]'
+
+  chpst -e /service/$service_name/env -u root eval "$SERVICES$service_name_upcase_ENABLE"
+  error_check "service_enable_pre"
 
   if [ "$?" -ne 0 ]; then
-    echo "$SERVICE_NAME enable script failure." >&2
+    echo "$service_name enable script failure." >&2
     exit ${E_BAD_ENABLE}
-  else printf "$SERVICE_NAME enabled\n"
+  else printf "$service_name enabled\n"
   fi
   return 0
 }
 
+###
+# Set up necessary service configs after running the enable var contents.
+###
 service_enable_post() {
   set +e
   echo "Enabling $SERVICE_NAME"
@@ -93,29 +112,32 @@ service_log_init() {
 main() {
   # TODO: use /etc/airstack/runtime.json instead of passed in file params
   #   runtime.json contains the combined service vars
-  init "$@"
+
+  # delete # init "$@"
 
   # service_settings_load #$SERVICE_SETTINGS
   # main_settings_load #$MAIN_SETTINGS
 
-  # Now use core loading functions to bring in the json objects.
-  . /package/airstack/core/core-json2env $MAIN_SETTINGS && \
-  core_settings_load
+  # delete  # # Now use core loading functions to bring in the json objects.
+  # delete  # /package/airstack/core/json2env-core $MAIN_SETTINGS && \
+  # delete  # core_settings_load
+  # delete
+  # delete  # /package/airstack/core/service-json2env $SERVICE_SETTINGS && \
+  # delete  # service_settings_load
 
-  . /package/airstack/core/service-json2env $SERVICE_SETTINGS && \
-  service_settings_load
+  for i in "$@"; do
+    service_enable_pre $i
+  done
 
-  service_enable_pre
-
-  service_run_init
-  printf "$SERVICE_NAME run is now:\n"
-  printf "$(cat /etc/sv/$SERVICE_NAME/run)\n"
-
-  service_log_init
-  printf "$SERVICE_NAME log is now:\n"
-  printf "$(cat /etc/sv/$SERVICE_NAME/log/run)\n"
-
-  service_enable_post
+# redo  # service_run_init
+# redo  # printf "$SERVICE_NAME run is now:\n"
+# redo  # printf "$(cat /etc/sv/$SERVICE_NAME/run)\n"
+# redo
+# redo  # service_log_init
+# redo  # printf "$SERVICE_NAME log is now:\n"
+# redo  # printf "$(cat /etc/sv/$SERVICE_NAME/log/run)\n"
+# redo
+# redo  # service_enable_post
 }
 
 main "$@"
diff --git a/services/runit/enable b/services/runit/enable
--- a/services/runit/enable
+++ b/services/runit/enable
@@ -1,35 +1,14 @@
-#!/bin/sh -e
+#!/bin/sh
 
 SOURCE=$0
 TMP_SERVICE=$(basename $(dirname $SOURCE))
 
-ERROR_MESSAGE_DEFAULT="enable script failure"
+DEBUG="${DEBUG_ENABLE-""}"
+[ -z "$DEBUG" ] || set -x -e
 
-###
-# usage: check_error <ERROR_MESSAGE> <ERROR_CODE>
-# Examples: check_error "The wheels just came off!" 110
-#           check_error "omgomgomg"
-#           check_error
-#
-# Uses passed in string for error message if provided.
-# If string not present, will use ERROR_MESSAGE_DEFAULT variable if present.
-# When a string is passed in, you can also pass in a custom error code.
-# Error code defaults to 113
-#
-# Reference: Bash exit code values [http://tldp.org/LDP/abs/html/exitcodes.html#EXITCODESREF]
-###
-check_error() {
-  if [ "$?" -ne 0 ]; then
-    set -x
-    local err_value; err_value="$?"
-    local err_msg; [ -z $1 ] && err_msg=${ERROR_MESSAGE_DEFAULT-"omg something bad"} || err_msg="$1"
-    echo "[$TMP_SERVICE] $err_msg\n" >&2
-    set +x
-    exit ${2-113}
-  fi
-}
-
-#=====
+# add airstack helpers if they exist:
+ERROR_MESSAGE_DEFAULT="[ERROR] Runit enable script failure -"
+[ -f "/package/airstack/core/airstack-helpers" ] && { . /package/airstack/core/airstack-helpers ;} || { printf "missing airstack-helpers. exiting.\n" && exit 113 ;}
 
 echo "Configuring $TMP_SERVICE"
 RUNIT_DIR="/etc/runit"
@@ -37,35 +16,45 @@ RUNSVDIR_DIR=$RUNIT_DIR/runsvdir
 
 # Remove any existing symlinked directory first.
 if [ -e $RUNIT_DIR ]; then
-	echo "Removing $RUNIT_DIR"
+	echo "Removing $RUNIT_DIR" && \
 	# TODO use msg_warn util
 	rm -rf $RUNIT_DIR
 fi
+error_check "symlink dir removal"
 
 # enable runlevel scripts
 ln -s /package/airstack/$TMP_SERVICE/runit $RUNIT_DIR
+error_check "symlink runlevel script"
 
 # Create runsvdir directories
 # See: http://smarden.org/runit/runlevels.html
 for i in single multi; do
   mkdir -p $RUNSVDIR_DIR/$i
 done
+error_check "create runsvdir directory"
 
-# /service should be canonical
 # set default level of single
 [ ! -L $RUNSVDIR_DIR/current ] && ln -sf $RUNSVDIR_DIR/single $RUNSVDIR_DIR/current
+error_check "symlink runsvdir default level"
+
+# /service should be canonical
 [ ! -L /service ] && ln -sf $RUNSVDIR_DIR/current /service
 
 # for debian compatibility, set up /etc/service.
-[ -L /etc/service ] && unlink /etc/service
-[ -d /etc/service ] && rm -rf /etc/service
+[ -L /etc/service ] && unlink /etc/service || true && \
+[ -d /etc/service ] && rm -rf /etc/service || true && \
 ln /service /etc/service
+error_check "symlink /service"
 
 # enable custom rc.local
 [ -e /etc/rc.local ] && (rm -f /etc/rc.local && ln -s /package/airstack/$TMP_SERVICE/rc.local /etc/)
+error_check "setup custom /etc/rc.local"
 
 # enable init utils
-RUNSVSTART_DIR=$(which runsvdir-start)
-ln -sf /etc/runit/2 $RUNSVSTART_DIR
-ln -s /etc/runit/2 /usr/local/bin/container-start
-ln -s /etc/runit/3 /usr/local/bin/container-stop
+RUNSVSTART_DIR=$(which runsvdir-start) && \
+ln -sf /etc/runit/2 $RUNSVSTART_DIR && \
+ln -s /etc/runit/2 /usr/local/bin/container-start && \
+ln -s /etc/runit/3 /usr/local/bin/container-stop && \
+error_check "symlink container commands"
+
+[ -z "$DEBUG" ] || set +x +e
diff --git a/services/runit/runit/2 b/services/runit/runit/2
--- a/services/runit/runit/2
+++ b/services/runit/runit/2
@@ -1,33 +1,19 @@
 #!/bin/sh -e
 
+
 PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
 
-msg() {
-    # bold
-    printf "\033[1m=> $@\033[m"
-}
+# add airstack helpers if they exist:
+ERROR_MESSAGE_DEFAULT="[ERROR] runit runlevel 2 -"
+[ -f "/package/airstack/core/airstack-helpers" ] && { . /package/airstack/core/airstack-helpers ;} || { printf "missing airstack-helpers. exiting.\n" && exit 113 ;}
 
-msg_ok() {
-    # bold/green
-    printf "\033[1m\033[32m OK\033[m\n"
-}
-
-msg_fail() {
-    # bold/red
-    printf "\033[1m\033[31m FAIL\033[m\n"
-}
-
-msg_warn() {
-    # bold/yellow
-    printf "\033[1m\033[33mWARNING: $@\033[m"
-}
-
-## END COMMON HEAD
 
 msg "Initializing Runit Level 2\n"
 
 # defaults to 'multi', but can pass in different runlevel.
 # /etc/runit/2 single
+
+set -x;
 
 TMP_RUNLEVEL=$1
 runsvchdir ${TMP_RUNLEVEL:="multi"} >/dev/null
@@ -35,10 +21,6 @@ runsvchdir ${TMP_RUNLEVEL:="multi"} >/dev/null
 # run in bg
 env - PATH=$PATH \
 /usr/bin/runsvdir -P /etc/service 'log: ...........................................................................................................................................................................................................................................................................................................................................................................................................' &
-
-msg "Starting /dev/log service in $TMP_RUNLEVEL mode\n"
-# /package/airstack/socklog-unix/enable 2>&1 && msg_ok
-/package/airstack/core/service-conf /package/airstack/core/config.json /package/airstack/socklog-unix/config.json 2>&1 && msg_ok
 
 # wait until socklog is up b4 proceeding
 # TODO put in healthcheck in check script instead of default
@@ -117,13 +99,22 @@ msg "Starting /dev/log service in $TMP_RUNLEVEL mode\n"
 # 1. combine each services config.json into one json object: <SERVICES>
 # 2. jq <SERVICES> * core/config.json * AIRSTACK_RUNTIME_VARS > runtime.json
 # 3. Use only runtime.json in service-conf
+
+# Create env files in /etc/airstack/env and /service/<service>/env
+
+/package/airstack/core/json2env-core
+/package/airstack/core/json2env-services
+
+msg "Starting /dev/log service in $TMP_RUNLEVEL mode\n"
+# /package/airstack/socklog-unix/enable 2>&1 && msg_ok
+
+# chpst -e /etc/airstack/env chpst -e env
+# /package/airstack/core/service-conf /package/airstack/core/config.json /package/airstack/socklog-unix/config.json
+/package/airstack/core/service-conf socklog-unix 2>&1 && msg_ok
+error_check ""
 if [ "$TMP_RUNLEVEL" != "single" ]; then
 	echo $(for i in $AIRSTACK_SERVICES; do echo /package/airstack/$i/config.json; done) | exec xargs -n1 sh /package/airstack/core/service-conf /package/airstack/core/config.json
 fi
-
-# Create env files in /etc/airstack/env and /service/<service>/env
-/package/airstack/core/json2env-core
-/package/airstack/core/json2env-services
 
 printf "services currently running:\n"
 update-service --list
