Enable service finish command

diff --git a/core/service-conf b/core/service-conf
--- a/core/service-conf
+++ b/core/service-conf
@@ -88,6 +88,33 @@ service_log_init() {
   return 0
 }
 
+###
+# Enable the finish command for our services
+###
+service_finish_init() {
+  set +e -x
+
+  local service_name; service_name="$1"
+  local cmd_name; cmd_name=$(find /env/$service_name/ -name '*_FINISH' | head -n1)
+
+
+  # don't do anything if blank
+  [ $(cat $cmd_name | wc -m) -gt 1 ] || return 0
+
+  BASEDIR=/etc/sv
+
+  # create runit service finish file
+  local cmdfile; cmd_file=$BASEDIR/$service_name/finish
+  echo "#!/bin/sh" > "$cmdfile"
+  echo "exec 2>&1" >> "$cmdfile"
+  cat "$cmd_name" >> "$cmdfile"
+
+  chmod ug+x $cmd_file
+  # core-error-check "log script failure"
+
+  return 0
+
+}
 
 ###
 # Set up necessary service configs after running the enable, run and log var contents.
