Created helper function to handle errors from shell commands

diff --git a/services/runit/enable b/services/runit/enable
--- a/services/runit/enable
+++ b/services/runit/enable
@@ -3,6 +3,34 @@
 SOURCE=$0
 TMP_SERVICE=$(basename $(dirname $SOURCE))
 
+ERROR_MESSAGE_DEFAULT="enable script failure"
+
+###
+# usage: check_error <ERROR_MESSAGE> <ERROR_CODE>
+# Examples: check_error "The wheels just came off!" 110
+#           check_error "omgomgomg"
+#           check_error 113
+#           check_error
+#
+# Uses passed in string for error message if provided.
+# If string not present, will use ERROR_MESSAGE_DEFAULT variable if present.
+# Will use passed in error_code, or defaults to error 113
+#
+# Reference: Bash exit code values [http://tldp.org/LDP/abs/html/exitcodes.html#EXITCODESREF]
+###
+check_error() {
+  if [ "$?" -ne 0 ]; then
+    set -x
+    local err_value; err_value="$?"
+    local err_msg; [ -z $1 ] && err_msg=${ERROR_MESSAGE_DEFAULT-"omg something bad"} || err_msg="$1"
+    echo "[$TMP_SERVICE] $err_msg\n" >&2
+    set +x
+    exit ${2-113}
+  fi
+}
+
+#=====
+
 echo "Configuring $TMP_SERVICE"
 RUNIT_DIR="/etc/runit"
 RUNSVDIR_DIR=$RUNIT_DIR/runsvdir
